const SUPABASE_URL='https://mfqlmsisrceyajspeeav.supabase.co';
const SUPABASE_KEY='sb_publishable_0UsdpSSgbF0pADTG-Viazw_vIphuNnE';
const client=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY);
const loginScreen=document.getElementById('loginScreen'),appShell=document.getElementById('appShell'),loginForm=document.getElementById('loginForm'),loginMessage=document.getElementById('loginMessage'),userEmail=document.getElementById('userEmail'),connectionStatus=document.getElementById('connectionStatus');
const titles={dashboard:'Visão geral',membros:'Gestão de Membros',visitantes:'Visitantes',eventos:'Eventos',intercessao:'Intercessão e Cuidado'};
const ministries=['Conect (Recepção)','Conect (Consolidação)','Intercessão','Louvor','Mídias (Fotos)','Mídias (Transmissão)','Mídias (Stories)','Café','Escolinha Kids','Projeção','Mesa de Som','Pastores','Líder e Discipulador'];
function escapeHtml(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}function formatDate(v){if(!v)return'—';return new Intl.DateTimeFormat('pt-BR',{dateStyle:'short',timeStyle:'short'}).format(new Date(v))}function setVisible(e,s){e.hidden=!s}
async function verifyAdmin(){const {data:{session}}=await client.auth.getSession();if(!session)return false;const {data,error}=await client.rpc('is_admin');if(error||data!==true){await client.auth.signOut();return false}userEmail.textContent=session.user.email||'';return true}
async function showApp(){setVisible(loginScreen,false);setVisible(appShell,true);connectionStatus.textContent='Conectado';await Promise.all([loadDashboard(),loadMembers(),loadVisitors(),loadEvents(),loadPrayer()])}async function showLogin(m=''){setVisible(appShell,false);setVisible(loginScreen,true);loginMessage.textContent=m}
loginForm.addEventListener('submit',async e=>{e.preventDefault();loginMessage.textContent='Entrando...';const {error}=await client.auth.signInWithPassword({email:document.getElementById('loginEmail').value.trim(),password:document.getElementById('loginPassword').value});if(error){loginMessage.textContent='Não foi possível entrar. Confira e-mail e senha.';return}if(!(await verifyAdmin())){showLogin('Este usuário não possui acesso administrativo.');return}loginMessage.textContent='';await showApp()});document.getElementById('logoutButton').addEventListener('click',async()=>{await client.auth.signOut();showLogin('Sessão encerrada.')});
const buttons=document.querySelectorAll('.nav-item'),views=document.querySelectorAll('.view'),pageTitle=document.getElementById('pageTitle');buttons.forEach(b=>b.addEventListener('click',()=>{const t=b.dataset.view;buttons.forEach(i=>i.classList.toggle('active',i===b));views.forEach(v=>v.classList.toggle('active',v.id===t));pageTitle.textContent=titles[t]||'Casa Forte Admin'}));
async function loadDashboard(){const {data,error}=await client.from('dashboard_resumo').select('*').single();if(error){connectionStatus.textContent='Erro ao carregar';return}document.getElementById('statVisitors').textContent=data.total_visitantes??0;document.getElementById('statSupport').textContent=data.visitantes_que_querem_acompanhamento??0;document.getElementById('statEvents').textContent=data.total_inscricoes??0;document.getElementById('statPrayer').textContent=data.pedidos_oracao_novos??0;document.getElementById('metricMonth').textContent=`${data.visitantes_ultimos_30_dias??0} visitantes nos últimos 30 dias`;document.getElementById('metricPastor').textContent=`${data.visitantes_que_querem_mensagem_pastor??0} querem mensagem do pastor`;document.getElementById('metricActiveEvents').textContent=`${data.total_eventos_ativos??0} eventos ativos`}
async function loadMembers(){const body=document.getElementById('membersBody'),empty=document.getElementById('membersEmpty');const {data,error}=await client.from('member_profiles').select('*').order('updated_at',{ascending:false}).limit(200);if(error){console.error(error);body.innerHTML='';empty.hidden=false;empty.querySelector('p').textContent='Erro ao carregar os membros.';return}body.innerHTML=(data||[]).map(m=>`<tr><td>${m.photo_url?`<img src="${m.photo_url}" alt="" style="width:48px;height:48px;border-radius:12px;object-fit:cover;vertical-align:middle;margin-right:8px">`:''}<strong>${escapeHtml(m.full_name||'Sem nome')}</strong></td><td>${escapeHtml(m.phone||'—')}<br><small>${escapeHtml(m.instagram||'')}</small></td><td>Nasc.: ${escapeHtml(m.birth_date||'—')}<br>Aceitou Jesus: ${escapeHtml(m.accepted_jesus_year||'—')}<br>Batizado: ${m.baptized===true?'Sim':m.baptized===false?'Não':'—'}<br>Outro ministério: ${m.came_from_other_ministry===true?'Sim':m.came_from_other_ministry===false?'Não':'—'}</td><td><span class="badge yes">${escapeHtml(m.church_role||'visitante')}</span></td><td>${escapeHtml((m.ministries||[]).join(', ')||'Nenhum')}</td><td><button onclick="editMember('${m.user_id}','${escapeHtml(m.church_role||'visitante')}','${escapeHtml((m.ministries||[]).join(', '))}')">Editar funções</button></td></tr>`).join('');empty.hidden=(data||[]).length>0}
window.editMember=async(userId,currentRole,currentMinistries)=>{const role=prompt('Status: visitante, frequentador, membro, voluntário, líder, discipulador, pastor ou administrador',currentRole);if(role===null)return;const selected=prompt(`Digite os ministérios separados por vírgula.\nOpções:\n${ministries.join('\n')}`,currentMinistries||'');if(selected===null)return;const list=selected.split(',').map(v=>v.trim()).filter(Boolean);const {error}=await client.from('member_profiles').update({church_role:role.trim().toLowerCase(),ministries:list,updated_at:new Date().toISOString()}).eq('user_id',userId);if(error){console.error(error);alert('Não foi possível atualizar.')}else loadMembers()};
async function loadVisitors(){const body=document.getElementById('visitorsBody'),empty=document.getElementById('visitorsEmpty');const {data,error}=await client.from('visitantes').select('*').order('created_at',{ascending:false}).limit(100);if(error){body.innerHTML='';empty.hidden=false;return}body.innerHTML=(data||[]).map(i=>`<tr><td><strong>${escapeHtml(i.nome)}</strong><br><small>${formatDate(i.created_at)}</small></td><td>${escapeHtml(i.telefone)}</td><td>${escapeHtml(i.bairro||'—')}</td><td>${escapeHtml(i.passo_fe||'—')}</td><td><span class="badge ${i.acompanhamento?'yes':''}">${i.acompanhamento?'Sim':'Não'}</span></td><td>${escapeHtml(i.status_acompanhamento||'novo')}</td></tr>`).join('');empty.hidden=(data||[]).length>0}
async function loadEvents(){const body=document.getElementById('eventsBody'),empty=document.getElementById('eventsEmpty');const {data,error}=await client.from('eventos').select('*').order('data_evento',{ascending:true}).limit(100);if(error){empty.hidden=false;return}body.innerHTML=(data||[]).map(i=>`<tr><td><strong>${escapeHtml(i.titulo)}</strong></td><td>${formatDate(i.data_evento)}</td><td>${escapeHtml(i.local||'—')}</td><td>${i.limite_vagas??'Livre'}</td><td><span class="badge ${i.ativo?'yes':''}">${i.ativo?'Ativo':'Encerrado'}</span></td></tr>`).join('');empty.hidden=(data||[]).length>0}
async function loadPrayer(){const body=document.getElementById('prayerBody'),empty=document.getElementById('prayerEmpty');const {data,error}=await client.from('pedidos_oracao').select('*').order('created_at',{ascending:false}).limit(100);if(error){empty.hidden=false;return}body.innerHTML=(data||[]).map(i=>`<tr><td>${escapeHtml(i.nome||'Anônimo')}</td><td>${escapeHtml(i.categoria||'—')}</td><td>${escapeHtml(i.pedido)}</td><td><span class="badge ${i.urgente?'yes':''}">${i.urgente?'Sim':'Não'}</span></td><td>${escapeHtml(i.status||'novo')}</td></tr>`).join('');empty.hidden=(data||[]).length>0}
document.getElementById('refreshMembers').addEventListener('click',loadMembers);document.getElementById('refreshVisitors').addEventListener('click',loadVisitors);document.getElementById('refreshEvents').addEventListener('click',loadEvents);document.getElementById('refreshPrayer').addEventListener('click',loadPrayer);(async()=>{if(await verifyAdmin())await showApp();else showLogin()})();