const SUPABASE_URL='https://mfqlmsisrceyajspeeav.supabase.co';
const SUPABASE_ANON_KEY='sb_publishable_0UsdpSSgbF0pADTG-Viazw_vIphuNnE';
const db=window.supabase.createClient(SUPABASE_URL,SUPABASE_ANON_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
const $=id=>document.getElementById(id),show=el=>el.classList.remove('cf-hidden'),hide=el=>el.classList.add('cf-hidden');
let members=[],ministries=[],editing=null;
function toast(text,isError){const t=$('toast');t.textContent=text;t.classList.toggle('is-error',!!isError);t.classList.add('is-visible');clearTimeout(t._timer);t._timer=setTimeout(()=>t.classList.remove('is-visible'),3200)}
function message(el,text,isError){el.textContent=text||'';el.className='cf-msg'+(text?(isError?' cf-msg-error':' cf-msg-ok'):'')}
function screen(name){['view-loading','view-auth','view-denied','view-app'].forEach(id=>hide($(id)));show($('view-'+name))}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function dateBR(v){if(!v)return'—';const d=new Date(v);return isNaN(d)?'—':d.toLocaleDateString('pt-BR')}
function yesNo(v){return v===true?'Sim':v===false?'Não':'—'}
async function start(){screen('loading');const{data:{session},error}=await db.auth.getSession();if(error||!session){screen('auth');return}await verify(session)}
async function verify(session){screen('loading');const{data,error}=await db.rpc('is_admin');if(error){message($('login-msg'),'Falha ao verificar permissão: '+error.message,true);screen('auth');return}if(data!==true){$('denied-email').textContent=session.user.email||'';screen('denied');return}$('hd-user').textContent=session.user.email||'';screen('app');await loadAll()}
$('btn-login').onclick=async()=>{const email=$('email').value.trim().toLowerCase(),password=$('password').value;if(!email||!password)return message($('login-msg'),'Preencha e-mail e senha.',true);const b=$('btn-login');b.disabled=true;b.textContent='Entrando…';message($('login-msg'),'');const{data,error}=await db.auth.signInWithPassword({email,password});b.disabled=false;b.textContent='Entrar no painel';if(error)return message($('login-msg'),error.message.toLowerCase().includes('invalid login')?'E-mail ou senha incorretos.':error.message,true);await verify(data.session)};
async function logout(){await db.auth.signOut();members=[];$('email').value='';$('password').value='';message($('login-msg'),'');screen('auth')}
$('btn-logout').onclick=logout;$('btn-logout-denied').onclick=logout;
async function loadAll(){await Promise.all([loadMinistries(),loadMembers(),loadVisitors(),loadPrayers(),loadEvents()]);summary()}
async function loadMinistries(){const{data,error}=await db.from('ministries').select('id,name,active').order('name');if(!error)ministries=data||[]}
async function loadMembers(){const{data,error}=await db.rpc('admin_list_members',{p_search:$('search').value.trim()||null,p_status:$('filter-status').value||null,p_limit:500,p_offset:0});if(error){$('members-list').innerHTML=`<div class="cf-empty">Não foi possível carregar a lista.<br>${esc(error.message)}</div>`;return}members=data||[];drawMembers()}
function drawMembers(){const box=$('members-list');if(!members.length){box.innerHTML='<div class="cf-empty">Nenhum membro encontrado com esses filtros.</div>';return}box.innerHTML=`<div class="cf-count">${members.length} ${members.length===1?'pessoa':'pessoas'}</div>`+members.map(m=>{const name=m.full_name||'Sem nome',initials=name.trim().split(/\s+/).slice(0,2).map(p=>p[0]).join('').toUpperCase()||'CF',photo=m.photo_url?`<img class="cf-avatar cf-avatar-sm" src="${esc(m.photo_url)}" alt="">`:`<div class="cf-avatar cf-avatar-sm">${esc(initials)}</div>`,pct=Number(m.completion_pct||0),star=m.star_member?' <span class="cf-star">★</span>':'',admin=m.is_admin?'<span class="cf-chip cf-chip-admin">Admin</span>':'',mins=(m.ministries||[]).map(n=>`<span class="cf-chip">${esc(n)}</span>`).join('');return `<article class="cf-member"><div class="cf-member-top">${photo}<div class="cf-member-main"><div class="cf-member-name">${esc(name)}${star}</div><div class="cf-member-meta">${esc(m.email||'')}</div><div class="cf-member-meta">${esc(m.phone||'Telefone não informado')}</div><div class="cf-chips cf-member-tags"><span class="cf-chip cf-chip-status">${esc(m.church_status||'visitante')}</span>${admin}${mins}</div><div class="cf-mini-track"><div class="cf-mini-fill" style="width:${pct}%"></div></div><div class="cf-member-meta" style="margin-top:5px;">Perfil ${pct}% preenchido</div></div></div><div class="cf-detail"><div class="cf-detail-item"><div class="cf-detail-label">Instagram</div>${esc(m.instagram||'—')}</div><div class="cf-detail-item"><div class="cf-detail-label">Nascimento</div>${dateBR(m.birth_date)}</div><div class="cf-detail-item"><div class="cf-detail-label">Aceitou Jesus</div>${esc(m.accepted_jesus_year||'—')}</div><div class="cf-detail-item"><div class="cf-detail-label">Outro ministério</div>${yesNo(m.came_from_other_ministry)}</div><div class="cf-detail-item"><div class="cf-detail-label">Batizado</div>${yesNo(m.baptized)}</div><div class="cf-detail-item"><div class="cf-detail-label">Cadastro</div>${dateBR(m.created_at)}</div></div><div class="cf-member-actions"><button class="cf-btn cf-btn-sm" data-edit="${m.id}">Editar</button><button class="cf-btn cf-btn-sm ${m.is_admin?'cf-btn-danger':'cf-btn-ghost'}" data-admin="${m.id}" data-value="${m.is_admin?'false':'true'}">${m.is_admin?'Remover admin':'Tornar admin'}</button></div></article>`}).join('');box.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>openModal(b.dataset.edit));box.querySelectorAll('[data-admin]').forEach(b=>b.onclick=()=>setAdmin(b.dataset.admin,b.dataset.value==='true'))}
let searchTimer;$('search').oninput=()=>{clearTimeout(searchTimer);searchTimer=setTimeout(loadMembers,350)};$('filter-status').onchange=loadMembers;
async function setAdmin(id,value){const m=members.find(x=>x.id===id),name=m?(m.full_name||m.email):'este membro';if(!confirm(value?`Dar acesso administrativo para ${name}?`:`Remover o acesso administrativo de ${name}?`))return;const{error}=await db.rpc('admin_set_admin',{p_member_id:id,p_is_admin:value});if(error)return toast(error.message,true);toast(value?'Acesso administrativo concedido':'Acesso administrativo removido');await loadMembers();summary()}
function openModal(id){editing=members.find(m=>m.id===id);if(!editing)return;$('modal-title').textContent=editing.full_name||'Editar membro';$('m-name').value=editing.full_name||'';$('m-phone').value=editing.phone||'';$('m-instagram').value=editing.instagram||'';$('m-birth').value=editing.birth_date||'';$('m-year').value=editing.accepted_jesus_year||'';$('m-previous').value=editing.came_from_other_ministry===null?'':String(editing.came_from_other_ministry);$('m-baptized').value=editing.baptized===null?'':String(editing.baptized);$('m-status').value=editing.church_status||'visitante';const marked=editing.ministry_ids||[];$('m-ministries').innerHTML=ministries.map(min=>`<label class="cf-check ${marked.includes(min.id)?'is-on':''}"><input type="checkbox" value="${min.id}" ${marked.includes(min.id)?'checked':''}><span>${esc(min.name)}</span></label>`).join('');$('m-ministries').querySelectorAll('input').forEach(cb=>cb.onchange=()=>cb.closest('.cf-check').classList.toggle('is-on',cb.checked));message($('modal-msg'),'');$('modal').classList.add('is-open')}
function closeModal(){$('modal').classList.remove('is-open');editing=null}$('modal-close').onclick=closeModal;$('modal').onclick=e=>{if(e.target===$('modal'))closeModal()};document.addEventListener('keydown',e=>{if(e.key==='Escape'&&$('modal').classList.contains('is-open'))closeModal()});
$('modal-save').onclick=async()=>{if(!editing)return;const b=$('modal-save');b.disabled=true;b.textContent='Salvando…';message($('modal-msg'),'');try{const year=$('m-year').value?parseInt($('m-year').value,10):null;let r=await db.rpc('admin_update_member',{p_member_id:editing.id,p_full_name:$('m-name').value.trim()||null,p_phone:$('m-phone').value.trim()||null,p_instagram:$('m-instagram').value.trim()||null,p_birth_date:$('m-birth').value||null,p_accepted_jesus_year:year,p_came_from_other_ministry:$('m-previous').value===''?null:$('m-previous').value==='true',p_baptized:$('m-baptized').value===''?null:$('m-baptized').value==='true'});if(r.error)throw r.error;if($('m-status').value!==editing.church_status){r=await db.rpc('admin_update_status',{p_member_id:editing.id,p_status:$('m-status').value});if(r.error)throw r.error}const ids=Array.from($('m-ministries').querySelectorAll('input:checked')).map(i=>i.value);r=await db.rpc('admin_set_ministries',{p_member_id:editing.id,p_ministry_ids:ids});if(r.error)throw r.error;closeModal();toast('Alterações salvas');await loadMembers();summary()}catch(err){message($('modal-msg'),'Não foi possível salvar: '+err.message,true)}finally{b.disabled=false;b.textContent='Salvar alterações'}};
async function loadVisitors(){const{data,error}=await db.from('visitantes').select('*').order('created_at',{ascending:false}).limit(300),box=$('visitors-list');if(error){box.innerHTML=`<div class="cf-empty">${esc(error.message)}</div>`;return}window._visitantes=data||[];box.innerHTML=!data.length?'<div class="cf-empty">Nenhum visitante cadastrado ainda.</div>':`<div class="cf-count">${data.length} ${data.length===1?'visitante':'visitantes'}</div>`+data.map(v=>`<article class="cf-record"><div class="cf-record-head"><div class="cf-record-title">${esc(v.nome)}</div><div class="cf-record-date">${dateBR(v.created_at)}</div></div><div class="cf-record-body">${esc(v.telefone||'')}${v.cidade?' · '+esc(v.cidade):''}${v.bairro?' · '+esc(v.bairro):''}</div><div class="cf-chips" style="margin-top:10px;"><span class="cf-chip cf-chip-status">${esc(v.status_acompanhamento||'novo')}</span>${v.acompanhamento?'<span class="cf-chip">Quer acompanhamento</span>':''}${v.mensagem_pastor?'<span class="cf-chip">Quer falar com o pastor</span>':''}</div></article>`).join('')}
async function loadPrayers(){const{data,error}=await db.from('pedidos_oracao').select('*').order('created_at',{ascending:false}).limit(300),box=$('prayers-list');if(error){box.innerHTML=`<div class="cf-empty">${esc(error.message)}</div>`;return}window._oracoes=data||[];box.innerHTML=!data.length?'<div class="cf-empty">Nenhum pedido de oração no momento.</div>':`<div class="cf-count">${data.length} ${data.length===1?'pedido':'pedidos'}</div>`+data.map(p=>`<article class="cf-record"><div class="cf-record-head"><div class="cf-record-title">${esc(p.nome||'Anônimo')}</div><div class="cf-record-date">${dateBR(p.created_at)}</div></div><div class="cf-record-body">${esc(p.pedido)}</div><div class="cf-chips" style="margin-top:10px;"><span class="cf-chip cf-chip-status">${esc(p.status||'novo')}</span>${p.urgente?'<span class="cf-chip cf-urgent">Urgente</span>':''}${p.categoria?`<span class="cf-chip">${esc(p.categoria)}</span>`:''}</div></article>`).join('')}
async function loadEvents(){const{data,error}=await db.from('eventos').select('*').order('data_evento',{ascending:false}).limit(120),box=$('events-list');if(error){box.innerHTML=`<div class="cf-empty">${esc(error.message)}</div>`;return}window._eventos=data||[];box.innerHTML=!data.length?'<div class="cf-empty">Nenhum evento cadastrado ainda.</div>':data.map(e=>`<article class="cf-record"><div class="cf-record-head"><div class="cf-record-title">${esc(e.titulo)}</div><div class="cf-record-date">${dateBR(e.data_evento)}</div></div><div class="cf-record-body">${esc(e.local||'Local a definir')}</div><div class="cf-chips" style="margin-top:10px;"><span class="cf-chip ${e.ativo?'cf-chip-status':''}">${e.ativo?'Ativo':'Encerrado'}</span></div></article>`).join('')}
function summary(){const v=window._visitantes||[],p=window._oracoes||[],e=window._eventos||[],cards=[['Membros cadastrados',members.length],['Perfis completos',members.filter(m=>m.star_member).length],['Administradores',members.filter(m=>m.is_admin).length],['Visitantes',v.length],['Pedidos novos',p.filter(x=>(x.status||'novo')==='novo').length],['Eventos ativos',e.filter(x=>x.ativo).length]];$('stats').innerHTML=cards.map(([l,n])=>`<div class="cf-stat"><div class="cf-stat-num">${n}</div><div class="cf-stat-label">${l}</div></div>`).join('')}
document.querySelectorAll('.cf-tab').forEach(tab=>tab.onclick=()=>{document.querySelectorAll('.cf-tab').forEach(t=>t.classList.remove('is-active'));document.querySelectorAll('.cf-panel').forEach(p=>p.classList.remove('is-active'));tab.classList.add('is-active');document.querySelector(`.cf-panel[data-panel="${tab.dataset.panel}"]`).classList.add('is-active')});
db.auth.onAuthStateChange(event=>{if(event==='SIGNED_OUT')screen('auth')});start();
