-- ============================================================================
-- BACKUP LÓGICO RESTAURÁVEL — Casa Forte Erechim
-- Projeto: CasaForte-Site-2026 (fjwkfpwraipxmcjlwssv)
-- Gerado em: 2026-07-24
-- Escopo: public.visitantes e public.pedidos_oracao (somente estrutura)
--
-- Este arquivo foi gerado por auditoria SOMENTE DE LEITURA do estado atual
-- do banco. Nenhum DDL/DML foi executado para produzi-lo.
--
-- Como usar:
--   Execute este arquivo inteiro em um banco Postgres/Supabase novo e vazio
--   para recriar exatamente estas duas integrações (estrutura, RLS,
--   políticas e permissões). Não contém dados nem credenciais.
-- ============================================================================


-- ----------------------------------------------------------------------------
-- 1) EXTENSÕES
-- ----------------------------------------------------------------------------
-- Nenhuma extensão além de plpgsql (padrão do Postgres) é necessária para
-- estas duas tabelas: não há colunas uuid, gen_random_uuid(), nem outros
-- recursos de extensão em uso por visitantes ou pedidos_oracao.
-- (O projeto de origem também tem uuid-ossp, pgcrypto, pg_stat_statements e
-- supabase_vault instalados, mas nenhum é referenciado por estas tabelas,
-- então não estão incluídos aqui.)


-- ----------------------------------------------------------------------------
-- 2) TABELA: public.visitantes
-- ----------------------------------------------------------------------------
create table if not exists public.visitantes (
  id                     bigint generated by default as identity primary key,
  nome                   text not null,
  telefone               text not null,
  cidade                 text not null,
  bairro                 text not null,
  acompanhamento         boolean not null default false,
  convidado_por          text,
  igreja_anterior        text,
  passo_fe               text not null,
  mensagem_pastor        boolean not null default false,
  experiencia_culto      text not null,
  voltar_culto           text not null,
  data_visita            date not null default current_date,
  status_acompanhamento  text not null default 'novo',
  created_at             timestamptz not null default now()
);

-- Sequence do id: criada e vinculada automaticamente pelo
-- "GENERATED BY DEFAULT AS IDENTITY" acima (public.visitantes_id_seq),
-- OWNED BY public.visitantes.id. Nenhum comando manual de CREATE SEQUENCE
-- é necessário.

-- CHECK constraints
alter table public.visitantes
  drop constraint if exists visitantes_passo_fe_check;
alter table public.visitantes
  add constraint visitantes_passo_fe_check
  check (passo_fe = any (array['aceitei_jesus','batizado','caminhada_longa','conhecendo']));

alter table public.visitantes
  drop constraint if exists visitantes_experiencia_culto_check;
alter table public.visitantes
  add constraint visitantes_experiencia_culto_check
  check (experiencia_culto = any (array['ruim','boa','ótima']));

alter table public.visitantes
  drop constraint if exists visitantes_voltar_culto_check;
alter table public.visitantes
  add constraint visitantes_voltar_culto_check
  check (voltar_culto = any (array['Sim, estarei no próximo culto','Não, fui só visitar']));

alter table public.visitantes
  drop constraint if exists visitantes_status_acompanhamento_check;
alter table public.visitantes
  add constraint visitantes_status_acompanhamento_check
  check (status_acompanhamento = any (array['novo','em_contato','acompanhado','concluido']));

-- Índices: nenhum índice adicional além do índice único do primary key
-- (visitantes_pkey), criado automaticamente pelo PRIMARY KEY acima.


-- ----------------------------------------------------------------------------
-- 3) TABELA: public.pedidos_oracao
-- ----------------------------------------------------------------------------
create table if not exists public.pedidos_oracao (
  id                bigint generated by default as identity primary key,
  nome              text not null,
  telefone          text not null,
  categoria         text not null,
  pedido            text not null,
  deseja_contato    boolean not null default false,
  urgente           boolean not null default false,
  status            text not null default 'novo',
  responsavel       text,
  observacoes       text,
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now()
);

-- Sequence do id: criada e vinculada automaticamente pelo
-- "GENERATED BY DEFAULT AS IDENTITY" acima (public.pedidos_oracao_id_seq),
-- OWNED BY public.pedidos_oracao.id.

-- CHECK constraints
alter table public.pedidos_oracao
  drop constraint if exists pedidos_oracao_categoria_check;
alter table public.pedidos_oracao
  add constraint pedidos_oracao_categoria_check
  check (categoria = any (array['saude','familia','vida_espiritual','casamento','financeiro','ansiedade_emocional','outro']));

alter table public.pedidos_oracao
  drop constraint if exists pedidos_oracao_status_check;
alter table public.pedidos_oracao
  add constraint pedidos_oracao_status_check
  check (status = any (array['novo','em_oracao','em_contato','concluido']));

alter table public.pedidos_oracao
  drop constraint if exists pedidos_oracao_pedido_check;
alter table public.pedidos_oracao
  add constraint pedidos_oracao_pedido_check
  check (length(trim(pedido)) >= 5 and length(trim(pedido)) <= 5000);

alter table public.pedidos_oracao
  drop constraint if exists pedidos_oracao_nome_check;
alter table public.pedidos_oracao
  add constraint pedidos_oracao_nome_check
  check (length(trim(nome)) >= 3);

alter table public.pedidos_oracao
  drop constraint if exists pedidos_oracao_telefone_check;
alter table public.pedidos_oracao
  add constraint pedidos_oracao_telefone_check
  check (length(trim(telefone)) >= 8);

-- Índices: nenhum índice adicional além do índice único do primary key
-- (pedidos_oracao_pkey), criado automaticamente pelo PRIMARY KEY acima.


-- ----------------------------------------------------------------------------
-- 4) FUNÇÃO E TRIGGER — updated_at de pedidos_oracao
-- ----------------------------------------------------------------------------
create or replace function public.set_pedidos_oracao_updated_at()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists pedidos_oracao_set_updated_at on public.pedidos_oracao;
create trigger pedidos_oracao_set_updated_at
  before update on public.pedidos_oracao
  for each row
  execute function public.set_pedidos_oracao_updated_at();

-- public.visitantes não possui função nem trigger próprios.


-- ----------------------------------------------------------------------------
-- 5) ROW LEVEL SECURITY
-- ----------------------------------------------------------------------------
alter table public.visitantes enable row level security;
alter table public.pedidos_oracao enable row level security;


-- ----------------------------------------------------------------------------
-- 6) POLICIES
-- ----------------------------------------------------------------------------
drop policy if exists visitantes_anon_insert on public.visitantes;
create policy visitantes_anon_insert
  on public.visitantes
  for insert
  to anon
  with check (
    length(trim(nome)) >= 3
    and length(trim(telefone)) >= 8
    and length(trim(cidade)) >= 2
    and length(trim(bairro)) >= 2
  );

drop policy if exists pedidos_oracao_anon_insert on public.pedidos_oracao;
create policy pedidos_oracao_anon_insert
  on public.pedidos_oracao
  for insert
  to anon
  with check (
    length(trim(nome)) >= 3
    and length(trim(telefone)) >= 8
    and length(trim(pedido)) between 5 and 5000
  );

-- Nenhuma política de SELECT, UPDATE ou DELETE existe para o público em
-- nenhuma das duas tabelas. Nenhuma política administrativa foi criada
-- ainda (reservado para quando o painel admin for construído, usando
-- member_profiles.is_admin = true).


-- ----------------------------------------------------------------------------
-- 7) GRANTS / REVOKES — anon, authenticated, service_role
-- ----------------------------------------------------------------------------
-- Privilégio mínimo: público (anon) só pode INSERT. authenticated não tem
-- nenhum privilégio de tabela hoje (nenhuma policy/uso administrativo ainda
-- construído). service_role mantém acesso total (papel interno do Supabase).

revoke all on public.visitantes from anon, authenticated;
grant insert on public.visitantes to anon;
grant usage on sequence public.visitantes_id_seq to anon;

revoke all on public.pedidos_oracao from anon, authenticated;
grant insert on public.pedidos_oracao to anon;
grant usage on sequence public.pedidos_oracao_id_seq to anon;

-- service_role mantém os privilégios padrão do Supabase (SELECT, INSERT,
-- UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER) em ambas as tabelas —
-- não é necessário GRANT explícito, pois já vem do papel interno do
-- projeto Supabase.

-- Observação de fidelidade: por padrão de privilégios do schema public do
-- Supabase, os papéis anon, authenticated e service_role já recebem USAGE
-- automático nas sequences de novas tabelas (default privileges do
-- projeto). O GRANT explícito de USAGE para anon acima é redundante com
-- esse padrão, mas foi mantido para deixar a intenção explícita e não
-- depender apenas do default do projeto.


-- ----------------------------------------------------------------------------
-- 8) OWNERSHIP
-- ----------------------------------------------------------------------------
-- Ambas as tabelas, suas sequences e a função set_pedidos_oracao_updated_at()
-- pertencem ao owner padrão usado pelo Supabase para objetos criados via
-- SQL Editor/migrations (papel "postgres"). Nenhuma dependência externa
-- (foreign keys para outras tabelas, como member_profiles) existe em
-- visitantes ou pedidos_oracao.


-- ----------------------------------------------------------------------------
-- 9) COMENTÁRIOS
-- ----------------------------------------------------------------------------
-- Nenhum comentário (COMMENT ON) está definido em nenhuma das duas tabelas
-- ou colunas no ambiente atual.


-- ============================================================================
-- 10) VERIFICAÇÕES PÓS-RESTORE (SOMENTE LEITURA — não altera dados)
-- ============================================================================

-- Estrutura das tabelas
select table_name, column_name, data_type, is_nullable, column_default
from information_schema.columns
where table_schema = 'public' and table_name in ('visitantes','pedidos_oracao')
order by table_name, ordinal_position;

-- Constraints ativas
select conrelid::regclass as tabela, conname, pg_get_constraintdef(oid) as definicao
from pg_constraint
where conrelid in ('public.visitantes'::regclass, 'public.pedidos_oracao'::regclass)
order by tabela, conname;

-- RLS ativado
select relname as tabela, relrowsecurity as rls_ativado
from pg_class
where relname in ('visitantes','pedidos_oracao');

-- Políticas ativas
select tablename, policyname, cmd, roles
from pg_policies
where schemaname = 'public' and tablename in ('visitantes','pedidos_oracao');

-- Grants ativos
select table_name, grantee, privilege_type
from information_schema.role_table_grants
where table_schema = 'public' and table_name in ('visitantes','pedidos_oracao')
order by table_name, grantee, privilege_type;

-- Trigger ativo
select tgname, tgrelid::regclass as tabela
from pg_trigger
where tgrelid in ('public.pedidos_oracao'::regclass) and not tgisinternal;

-- Contagem de registros (informativo)
select
  (select count(*) from public.visitantes)      as total_visitantes,
  (select count(*) from public.pedidos_oracao)  as total_pedidos_oracao;

-- ============================================================================
-- FIM DO BACKUP
-- ============================================================================
