create table public.whatsapp_conversations (
  id bigint generated by default as identity primary key,
  phone text not null unique check (phone ~ '^[0-9]{8,20}$'),
  contact_name text,
  last_message_at timestamptz not null default now(),
  last_message_preview text,
  unread_count integer not null default 0 check (unread_count >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.whatsapp_messages (
  id bigint generated by default as identity primary key,
  conversation_id bigint not null references public.whatsapp_conversations(id) on delete cascade,
  wa_message_id text not null unique,
  direction text not null check (direction in ('inbound', 'outbound')),
  message_type text not null default 'text',
  body text,
  media_id text,
  status text not null default 'received' check (status in ('received', 'sent', 'delivered', 'read', 'failed')),
  error_message text,
  sent_at timestamptz not null default now(),
  raw_payload jsonb,
  created_at timestamptz not null default now()
);

create index whatsapp_conversations_recent_idx on public.whatsapp_conversations (last_message_at desc);
create index whatsapp_messages_conversation_idx on public.whatsapp_messages (conversation_id, sent_at);

alter table public.whatsapp_conversations enable row level security;
alter table public.whatsapp_messages enable row level security;

create policy "Administradores consultam conversas do WhatsApp"
on public.whatsapp_conversations for select to authenticated
using ((select public.is_admin()));

create policy "Administradores atualizam conversas do WhatsApp"
on public.whatsapp_conversations for update to authenticated
using ((select public.is_admin())) with check ((select public.is_admin()));

create policy "Administradores consultam mensagens do WhatsApp"
on public.whatsapp_messages for select to authenticated
using ((select public.is_admin()));

grant select, update on public.whatsapp_conversations to authenticated;
grant select on public.whatsapp_messages to authenticated;
grant all on public.whatsapp_conversations, public.whatsapp_messages to service_role;
grant usage, select on sequence public.whatsapp_conversations_id_seq, public.whatsapp_messages_id_seq to service_role;
