create table public.web_push_subscriptions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  endpoint text not null unique,
  p256dh text not null,
  auth_key text not null,
  enabled_events text[] not null default array[
    'domingo-casa',
    'quarta-ensino',
    'sexta-oracao'
  ]::text[],
  user_agent text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  last_success_at timestamptz,
  failure_count integer not null default 0,
  constraint web_push_subscriptions_endpoint_length_check
    check (length(endpoint) between 30 and 4096),
  constraint web_push_subscriptions_p256dh_length_check
    check (length(p256dh) between 20 and 512),
  constraint web_push_subscriptions_auth_key_length_check
    check (length(auth_key) between 8 and 256),
  constraint web_push_subscriptions_user_agent_length_check
    check (user_agent is null or length(user_agent) <= 500),
  constraint web_push_subscriptions_events_check
    check (
      cardinality(enabled_events) between 1 and 3
      and enabled_events <@ array[
        'domingo-casa',
        'quarta-ensino',
        'sexta-oracao'
      ]::text[]
    ),
  constraint web_push_subscriptions_failure_count_check
    check (failure_count between 0 and 100)
);

comment on table public.web_push_subscriptions is
  'Inscrições Web Push dos aparelhos autorizados por membros da Casa Forte.';

create index web_push_subscriptions_user_id_idx
  on public.web_push_subscriptions (user_id);

create index web_push_subscriptions_enabled_events_idx
  on public.web_push_subscriptions using gin (enabled_events);

alter table public.web_push_subscriptions enable row level security;

revoke all on table public.web_push_subscriptions from anon;
grant select, insert, update, delete
  on table public.web_push_subscriptions to authenticated;

create policy "Membro consulta as proprias notificacoes"
  on public.web_push_subscriptions
  for select
  to authenticated
  using ((select auth.uid()) = user_id);

create policy "Membro cadastra o proprio aparelho"
  on public.web_push_subscriptions
  for insert
  to authenticated
  with check (
    (select auth.uid()) = user_id
    and exists (
      select 1
      from public.member_profiles
      where member_profiles.user_id = (select auth.uid())
        and (
          member_profiles.approval_status = 'approved'
          or member_profiles.is_admin = true
        )
    )
  );

create policy "Membro atualiza o proprio aparelho"
  on public.web_push_subscriptions
  for update
  to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

create policy "Membro remove o proprio aparelho"
  on public.web_push_subscriptions
  for delete
  to authenticated
  using ((select auth.uid()) = user_id);

create table public.web_push_deliveries (
  id bigint generated by default as identity primary key,
  subscription_id uuid not null
    references public.web_push_subscriptions(id) on delete cascade,
  event_key text not null,
  event_date date not null,
  status text not null default 'pending',
  attempted_at timestamptz not null default now(),
  sent_at timestamptz,
  error_code integer,
  constraint web_push_deliveries_event_check
    check (event_key in ('domingo-casa', 'quarta-ensino', 'sexta-oracao')),
  constraint web_push_deliveries_status_check
    check (status in ('pending', 'sent', 'failed')),
  constraint web_push_deliveries_subscription_event_key
    unique (subscription_id, event_key, event_date)
);

comment on table public.web_push_deliveries is
  'Controle interno de idempotência dos lembretes Web Push.';

create index web_push_deliveries_event_idx
  on public.web_push_deliveries (event_date desc, event_key, status);

alter table public.web_push_deliveries enable row level security;

revoke all on table public.web_push_deliveries from anon, authenticated;
grant select, insert, update, delete
  on table public.web_push_deliveries to service_role;
grant usage, select on sequence public.web_push_deliveries_id_seq
  to service_role;

do $$
begin
  if not exists (
    select 1 from cron.job where jobname = 'notificacao-push-domingo'
  ) then
    perform cron.schedule(
      'notificacao-push-domingo',
      '0 20 * * 0',
      $job$
        select net.http_get(
          url := 'https://www.casaforteerechim.app.br/api/cron/push-culto-reminders?event=domingo-casa',
          headers := jsonb_build_object(
            'Authorization',
            'Bearer ' || (
              select decrypted_secret
              from vault.decrypted_secrets
              where name = 'checkin_cron_secret'
              limit 1
            )
          ),
          timeout_milliseconds := 30000
        );
      $job$
    );
  end if;

  if not exists (
    select 1 from cron.job where jobname = 'notificacao-push-quarta'
  ) then
    perform cron.schedule(
      'notificacao-push-quarta',
      '30 20 * * 3',
      $job$
        select net.http_get(
          url := 'https://www.casaforteerechim.app.br/api/cron/push-culto-reminders?event=quarta-ensino',
          headers := jsonb_build_object(
            'Authorization',
            'Bearer ' || (
              select decrypted_secret
              from vault.decrypted_secrets
              where name = 'checkin_cron_secret'
              limit 1
            )
          ),
          timeout_milliseconds := 30000
        );
      $job$
    );
  end if;

  if not exists (
    select 1 from cron.job where jobname = 'notificacao-push-sexta'
  ) then
    perform cron.schedule(
      'notificacao-push-sexta',
      '30 20 * * 5',
      $job$
        select net.http_get(
          url := 'https://www.casaforteerechim.app.br/api/cron/push-culto-reminders?event=sexta-oracao',
          headers := jsonb_build_object(
            'Authorization',
            'Bearer ' || (
              select decrypted_secret
              from vault.decrypted_secrets
              where name = 'checkin_cron_secret'
              limit 1
            )
          ),
          timeout_milliseconds := 30000
        );
      $job$
    );
  end if;
end
$$;
