create table public.culto_checkins (
  id bigint generated by default as identity primary key,
  event_key text not null,
  event_date date not null,
  event_title text not null,
  nome text not null,
  telefone text not null,
  resposta text not null,
  created_at timestamptz not null default now(),
  constraint culto_checkins_event_key_check
    check (event_key = 'domingo-casa'),
  constraint culto_checkins_event_title_check
    check (event_title = 'Culto Domingo na Casa'),
  constraint culto_checkins_nome_check
    check (length(btrim(nome)) between 3 and 120),
  constraint culto_checkins_telefone_check
    check (telefone ~ '^[0-9]{10,13}$'),
  constraint culto_checkins_resposta_check
    check (resposta in ('presencial', 'nao_vou', 'live')),
  constraint culto_checkins_evento_telefone_key
    unique (event_key, event_date, telefone)
);

comment on table public.culto_checkins is
  'Respostas do pré-check-in do próximo Culto Domingo na Casa.';

create index culto_checkins_evento_resposta_idx
  on public.culto_checkins (event_date desc, resposta);

create index culto_checkins_created_at_idx
  on public.culto_checkins (created_at desc);

alter table public.culto_checkins enable row level security;

grant insert on table public.culto_checkins to anon, authenticated;
grant select on table public.culto_checkins to authenticated;
grant usage, select on sequence public.culto_checkins_id_seq to anon, authenticated;

create policy "Publico registra pre check-in futuro"
  on public.culto_checkins
  for insert
  to anon, authenticated
  with check (
    event_key = 'domingo-casa'
    and event_title = 'Culto Domingo na Casa'
    and event_date between current_date and (current_date + 14)
  );

create policy "Administradores consultam pre check-ins"
  on public.culto_checkins
  for select
  to authenticated
  using (
    (select auth.uid()) is not null
    and exists (
      select 1
      from public.member_profiles
      where member_profiles.user_id = (select auth.uid())
        and member_profiles.is_admin = true
    )
  );
