-- Solicitações públicas da Área de Membros.
-- A conta Auth só nasce depois da aprovação explícita de um administrador.

create table if not exists public.member_applications (
  id bigint generated by default as identity primary key,
  full_name text not null,
  email text not null,
  phone text not null,
  status text not null default 'pending',
  auth_user_id uuid references auth.users(id) on delete set null,
  reviewed_at timestamptz,
  reviewed_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint member_applications_full_name_check
    check (length(btrim(full_name)) between 3 and 160),
  constraint member_applications_email_check
    check (
      email = lower(btrim(email))
      and length(email) between 5 and 254
      and email like '%@%'
    ),
  constraint member_applications_phone_check
    check (length(btrim(phone)) between 8 and 30),
  constraint member_applications_status_check
    check (status in ('pending', 'invited', 'rejected'))
);

create unique index if not exists member_applications_email_unique_idx
  on public.member_applications (lower(email));

create index if not exists member_applications_status_created_idx
  on public.member_applications (status, created_at desc);

alter table public.member_applications enable row level security;

drop policy if exists member_applications_public_insert
  on public.member_applications;

create policy member_applications_public_insert
  on public.member_applications
  for insert
  to anon
  with check (
    status = 'pending'
    and auth_user_id is null
    and reviewed_at is null
    and reviewed_by is null
  );

drop policy if exists member_applications_admin_select
  on public.member_applications;

create policy member_applications_admin_select
  on public.member_applications
  for select
  to authenticated
  using (public.is_admin());

drop policy if exists member_applications_admin_update
  on public.member_applications;

create policy member_applications_admin_update
  on public.member_applications
  for update
  to authenticated
  using (public.is_admin())
  with check (public.is_admin());

revoke all on public.member_applications from anon, authenticated;
revoke all on sequence public.member_applications_id_seq from anon, authenticated;

grant insert (full_name, email, phone)
  on public.member_applications
  to anon;

grant usage, select
  on sequence public.member_applications_id_seq
  to anon;

grant select
  on public.member_applications
  to authenticated;

grant update (
  status,
  auth_user_id,
  reviewed_at,
  reviewed_by,
  updated_at
) on public.member_applications
  to authenticated;

comment on table public.member_applications is
  'Pedidos de entrada na Área da Família. Nenhum papel público recebe DELETE.';

comment on column public.member_applications.status is
  'pending: aguarda revisão; invited: convite enviado; rejected: não aprovado.';
